add arn for cloudwatch policy to role
Sage-Bionetworks/veoibd-aws-infra pull request #14
Opened 2019-10-18 23:09 UTC by kdaily

2019-10-19 00:03 UTC, zaro0508 requested changes
line 40:
  the type needs to be a `AWS::IAM::ManagedPolicy` not `AWS::IAM::Policy`

take a look at the doc https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html

2019-10-19 00:03 UTC, zaro0508 commented on templates/veoibd.yaml
> +        - !GetAtt PublishToCloudwatchPolicy.Arn
this need to be `!Ref PublishToCloudwatchPolicy`

From https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html
```
Ref

When you pass the logical ID of this resource to the intrinsic Ref function, Ref returns the ARN.

In the following sample, the Ref function returns the ARN of the CreateTestDBPolicy managed policy, such as arn:aws:iam::123456789012:policy/teststack-CreateTestDBPolicy-16M23YE3CS700.
```

2019-10-21 16:25 UTC, kdaily commented on templates/veoibd.yaml
> +        - !GetAtt PublishToCloudwatchPolicy.Arn
```suggestion
        - !Ref PublishToCloudwatchPolicy
```

2019-10-21 18:03 UTC, zaro0508 approved these changes

2019-10-21 18:07 UTC, merged